### PR TITLE
Make logo work in dark mode

### PR DESCRIPTION
**Pull request by jbrooksuk**
This PR adds a white border around the "Laravel Pulse" text to make it visible in dark mode. We use the same technique on other packages.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Okay, all I did was add a border to the text in Figma and now it's rendering weirdly in GitHub, but is fine in Finder.

CleanShot 2024-05-02 at 08 36 37@2x

**Comment by jbrooksuk** [comment]
🤷‍♂️ I've no idea what's causing that.

**Comment by jessarcher** [comment]
We previously had the outline, which I never liked the look of much on dark mode, until https://github.com/laravel/pulse/pull/97, where they made it responsive based on the system preference.

It works well on Firefox/Linux, but it sounds like there are browsers where it doesn't?

image
image

**Comment by jbrooksuk** [comment]
@jessarcher it works for me, but I think the issue may be on GitHub mobile? https://github.com/laravel/pulse/issues/357

**Pull request closed without merging**
