### PR TITLE
[1.x] Add mariadb test workflow

### PR DESCRIPTION
**Pull request by AustinW**
This PR simply adds support for MariaDB. Not many changes as most of the configurations are congruent with MySQL.

### CODE REVIEW

**Comment by timacdonald** [comment]
@AustinW Pulse already supports MariaDB via the `mysql` driver.

I've remove the configuration changes and removed the matrix from the MariaDB workflow.

We currently only run the full matrix against MySQL and then run once against the other DB types.

**Review by timacdonald — APPROVED** [review]

**Comment by AustinW** [comment]
@timacdonald We use this package in our project: https://github.com/ybr-nx/laravel-mariadb?tab=readme-ov-file#configure-only-larvel-53-and-54 which requires us to set the driver to `mariadb`. We had to modify the migration manually for the migration to run. It's not a big deal, but it'd be nice to include that case in the migration.

**Comment by timacdonald** [comment]
I see. As that is not a first party package I don't think we should account for it in our base migration. Will ask the team for their thoughts.

**Comment by jessarcher** [comment]
> I see. As that is not a first party package I don't think we should account for it in our base migration. Will ask the team for their thoughts.

I agree. It's easy enough to tweak the migration if needed. That package is pretty old, too - I wonder whether it's needed any longer?

**Pull request merged**
