### PR TITLE
[1.x] Added the ability to localize the interface

### PR DESCRIPTION
**Pull request by andrey-helldar**
I think it would be great to be able to localize the interface, so I suggest you consider this PR.

Related to https://github.com/laravel/pulse/issues/110

### CODE REVIEW

**Comment by andrey-helldar** [comment]
I don’t know how to solve the problem of a static analyzer complaining about the following code:

```php
public function periodForHumans(): string
{
    return match ($this->period) {
        '6_hours' => __('6 hours'),
        '24_hours' => __('24 hours'),
        '7_days' => __('7 days'),
        default => __('hour'),
    };
}
```

image

```
 ------ ------------------------------------------------------------------------------------------------------------
  Line   Livewire\Concerns\HasPeriod.php (in context of class Laravel\Pulse\Livewire\Usage)
 ------ ------------------------------------------------------------------------------------------------------------
  36     Method Laravel\Pulse\Livewire\Usage::periodForHumans() should return string but returns array|string|null.
 ------ ------------------------------------------------------------------------------------------------------------
```

**Comment by taylorotwell** [comment]
I honestly don't really want to explore this for Pulse at this time since it is not a customer facing tool.

**Comment by andrey-helldar** [comment]
Reasonable. But many developers localize their tools anyway.

I have seen the use of localizations for programs such as JetBrains PhpStorm, Fleet, WebStorm, VSCode, SublimeText and Photoshop. Even for my fork with a [list of routes](https://github.com/TheDragonCode/pretty-routes?tab=readme-ov-file#pretty-routes-for-laravel), they once asked me to do localization.

So I'll just wait for the right moment 🙂

**Comment by avinmaster** [comment]
Plus one here, nowadays, clients are not just basic users, they asked to add for them a dashboard for checking queues, exceptions, etc. and I exposed them this page, now I need a translation.

**Pull request closed without merging**
