### PR TITLE
Carbon v3

### PR DESCRIPTION
**Pull request by driesvints**

### CODE REVIEW

**Review by nunomaduro — APPROVED** [review]

**Comment by timacdonald** [comment]
Pushed a fix to maintain the `int` value returned from `diffInMilliseconds`. This return type changed in Carbon v3.

Although not a major issue, it is a potential change in functionality if the config were to contain a float value.

**Review by timacdonald — APPROVED** [review]

**Comment by timacdonald** [comment]
I would prefer to keep this in draft until v3 is actually released and we know for sure what all the breaking changes are.

Otherwise we merge this and they tag additional breaking changes in future beta release and we have to re-review.

**Comment by driesvints** [comment]
@timacdonald Should only be bug fixes from now on normally.

**Comment by driesvints** [comment]
Stable release out now.

**Pull request merged**
